const QUEST_MODULE_OPERACION = 'operacion';
const QUEST_MODULE_CASOS = 'casos';
const QUEST_MODULE_MAPA = 'mapa';
const QUEST_MODULE_PERFILES = 'perfiles';
const QUEST_MODULE_HERRAMIENTAS = 'herramientas';

export {
  QUEST_MODULE_OPERACION,
  QUEST_MODULE_CASOS,
  QUEST_MODULE_MAPA,
  QUEST_MODULE_PERFILES,
  QUEST_MODULE_HERRAMIENTAS,
};
