const QUEST_SCREEN_HOME = 'home';
const QUEST_SCREEN_CASES = 'cases';
const QUEST_SCREEN_CASE_DETAIL = 'case-detail';
const QUEST_SCREEN_POIS = 'pois';
const QUEST_SCREEN_POI_DETAIL = 'poi-detail';
const QUEST_SCREEN_VILLAINS = 'villains';
const QUEST_SCREEN_VILLAIN_DETAIL = 'villain-detail';

export {
  QUEST_SCREEN_HOME,
  QUEST_SCREEN_CASES,
  QUEST_SCREEN_CASE_DETAIL,
  QUEST_SCREEN_POIS,
  QUEST_SCREEN_POI_DETAIL,
  QUEST_SCREEN_VILLAINS,
  QUEST_SCREEN_VILLAIN_DETAIL,
};
